### ISSUE TITLE
강의 검색에서 썸네일 관련 요청사항

### ISSUE THREAD

**Issue by oikkoikk** [4m9d/sroom-be#25]
## 개요 🔖
- 유튜브가 기본 제공하는 썸네일은 3:4 비율로 상하 레터박스가 생김
- 이에 따라 영상별로 16:9 비율 썸네일이 존재하는지 확인하는 과정을 포함하여 썸네일 링크를 확정하고 있음
- 현재 '강의 검색' 페이지에서 유튜브 썸네일을 불러오는 과정 시간 소요가 상당함

<br>

## 이유 🤔
- 현재 '강의 검색'페이지에서 유튜브 썸네일을 불러오는 과정 시간 소요가 상당함
- maxreqresult.jpg가 있는지 파악할 필요 없이, 공통적으로 썸네일을 가져올 필요가 있음

<br>

## 세부 사항 📃
- mqdefault.jpg를 불러오면 오래된 영상에서도 정상적으로 16:9 비율로 썸네일을 불러올 수 있는 것을 확인
![오래된 영상에서의 mqdefault.jpg](https://i1.ytimg.com/vi/k_fAjewwx1k/mqdefault.jpg)

- 강의 검색에서는 mqdefault.jpg만 가져오는 것으로 하고, 상세 정보 모달에서만 maxreqresult.jpg가 있는지 확인 후 사용하는 것이 어떤지

**Comment by D-w-nJ** [comment]
확인했습니다! 오늘중으로 pr 날리겠습니다

**Comment by D-w-nJ** [comment]
다음 작업도 함께 진행하겠습니다

- video 상세검색에 영상길이 추가
- 재생목록 상세검색에 총 영상길이 추가
