### ISSUE TITLE
[SWM-179] 강의 상세 정보 API param 구조 개선 요청

### ISSUE THREAD

**Issue by oikkoikk** [4m9d/sroom-be#28]
## 개요 🔖
- 강의 상세 정보 API 호출 시 필요한 `is_playlist` 생략 및 response에 `isEnrolled` 포함을 요청함

<br>

### `is_playlist` query parameter
- 현재 강의 상세 정보 API 호출 시 해당 영상이 재생목록인지 단일 영상인지를 구분해주는 `is_playlist`를 query에 넣어서 보내고 있음
  - 해당 방식은 정보 노출 및 위변조가 가능한 클라이언트에서 관리하기 부적절함
### `isEnrolled` response
- 현재 클라이언트에서는 해당 영상을 사용자가 이미 등록하였는지를 `isEnrolled`를 강의 상세 정보 API호출에서는 받지 못하고, 강의 검색에서 받은 데이터를 재사용하고 있음
  - 해당 방식은 정보 노출 및 위변조가 가능한 클라이언트에서 관리하기 부적절함
  - 사용자가 직접 URL에서 쿼리를 변조하면 그에 따라 모달 UI가 검증없이 등록 / 미등록 상태로 변하게 될 가능성이 있음

<br>

## 세부 사항 📃
- 강의 상세 정보 API 호출 시 `is_playlist` query parameter 생략
- 강의 상세 정보 API 호출 시 response에 `isEnrolled` 포함

**Comment by D-w-nJ** [comment]
description, title에 html 문자가 들어가는 오류 해결도 포함시키겠습니다. 감사합니다
